import 'package:flutter/material.dart';

final Map<String, IconData> availableIcons = {
  'Inventory': Icons.inventory_2,
  'Books': Icons.menu_book,
  'Clothing': Icons.checkroom,
  'Kitchen': Icons.kitchen,
  'Furniture': Icons.chair,
  'Sports': Icons.sports_soccer,
  'Toys': Icons.toys,
  'Beauty': Icons.face,
  'Automotive': Icons.directions_car,
  'Home': Icons.home,
  'Electronics': Icons.devices,
  'Food': Icons.restaurant,
  'Drinks': Icons.local_drink,
  'Medicine': Icons.medical_services,
  'Tools': Icons.build,
  'Garden': Icons.eco,
  'Pet Supplies': Icons.pets,
  'Office': Icons.business_center,
  'Music': Icons.music_note,
  'Movies': Icons.movie,
  'Games': Icons.sports_esports,
  'Jewelry': Icons.diamond,
  'Shoes': Icons.shopping_bag,
  'Accessories': Icons.watch,
  'Baby': Icons.child_care,
  'Health': Icons.favorite,
  'Fitness': Icons.fitness_center,
  'Travel': Icons.flight,
  'Stationery': Icons.edit,
  'Art Supplies': Icons.palette,
  'Hardware': Icons.hardware,
  'Appliances': Icons.microwave,
  'Lighting': Icons.lightbulb,
  'Bathroom': Icons.bathtub,
  'Bedroom': Icons.bed,
  'Cleaning': Icons.cleaning_services,
  'Storage': Icons.inventory,
  'Packaging': Icons.inbox,
  'Labels': Icons.label,
  'Barcode': Icons.qr_code_scanner,
  'Cash Register': Icons.point_of_sale,
  'Shopping Cart': Icons.shopping_cart,
  'Store': Icons.store,
  'Warehouse': Icons.warehouse,
  'Delivery': Icons.local_shipping,
  'Payment': Icons.payment,
  'Discount': Icons.discount,
  'Gift': Icons.card_giftcard,
  'Star': Icons.star,
  'Category': Icons.category,
  'Folder': Icons.folder,
  'Box': Icons.inbox_outlined,
};

